In [4]:
def librerias():

    '''Empezamos importando las librerìas que se va a utilizar'''

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.svm import SVC
from sklearn import metrics
import matplotlib.pyplot as plt
import seaborn as sn
import pandas as pd
from numpy import array

print(librerias.__doc__)

Empezamos importando las librerìas que se va a utilizar


In [9]:
def importarData():
    
    ''' Creamos la funciòn para importar el Dataset acerca de los diferentes Vinos de la librerìa scikit-learn '''

df = datasets.load_wine()

print(importarData.__doc__)

 Creamos la funciòn para importar el Dataset acerca de los diferentes Vinos de la librerìa scikit-learn 


In [13]:
def imprimirCaract():
    
    ''' Mandamos a imprimir las caracteristicas(X) con las que cuenta el Dataset'''

print("Features:\n", df.feature_names, '\n')

print(imprimirCaract.__doc__)

Features:
 ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline'] 

 Mandamos a imprimir las caracteristicas(X) con las que cuenta el Dataset


In [14]:
def imprimirEtiq():
    
    ''' Mandamos a imprimir las etiquetas(y) con las que cuenta el Dataset'''

print("Labels:\n", df.target_names, '\n')

print(imprimirEtiq.__doc__)

Labels:
 ['class_0' 'class_1' 'class_2'] 

 Mandamos a imprimir las etiquetas(y) con las que cuenta el Dataset


In [16]:
def imprimirNum():
    
    ''' Mandamos a imprimir el nùmero exactos de datos  que existen en el Dataset'''

print("Shape:\n", df.data.shape, '\n')
    
print(imprimirNum.__doc__)

Shape:
 (178, 13) 

 Mandamos a imprimir el nùmero exactos de datos  que existen en el Dataset


In [18]:
def imprimirRec():
    
    ''' Se imprimen los 5 mejores records'''

print("Top five records:\n", df.data[0:5], '\n')
    
print(imprimirRec.__doc__)

Top five records:
 [[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
  2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 1.120e+01 1.000e+02 2.650e+00 2.760e+00
  2.600e-01 1.280e+00 4.380e+00 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 1.860e+01 1.010e+02 2.800e+00 3.240e+00
  3.000e-01 2.810e+00 5.680e+00 1.030e+00 3.170e+00 1.185e+03]
 [1.437e+01 1.950e+00 2.500e+00 1.680e+01 1.130e+02 3.850e+00 3.490e+00
  2.400e-01 2.180e+00 7.800e+00 8.600e-01 3.450e+00 1.480e+03]
 [1.324e+01 2.590e+00 2.870e+00 2.100e+01 1.180e+02 2.800e+00 2.690e+00
  3.900e-01 1.820e+00 4.320e+00 1.040e+00 2.930e+00 7.350e+02]] 

 Se imprimen los 5 mejores records


In [34]:
def decX():
    
     ''' Se define la variable X que en este caso son sus caracteristicas'''
    
X= df.data
print(X, '\n')

    
    
print(decX.__doc__)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]] 

 Se define la variable X que en este caso son sus caracteristicas


In [35]:
def decY():
    
     ''' Se define la variable y que en este caso son sus etiquetas'''
    
y= df.target
print(y, '\n')
    
    
print(decY.__doc__)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2] 

 Se define la variable y que en este caso son sus etiquetas


In [36]:
def crearFunc():
    
    ''' Creamos la funciòn para poder entrenar el modelo, se toma el 70% de datos para entrenar
y el 30% de datos se toma para realizar las pruebas al azar '''

X_train, X_test, y_train, y_test = train_test_split(df.data, df.target, test_size=0.3, random_state=109)
    
print(crearFunc.__doc__)

 Creamos la funciòn para poder entrenar el modelo, se toma el 70% de datos para entrenar
y el 30% de datos se toma para realizar las pruebas al azar 


In [37]:
def crearMod():
    
    ''' Creamos la funciòn para crear al clasificador mediante el Kernel linear'''

clf = svm.SVC(kernel='linear')
    
print(crearMod.__doc__)

 Creamos la funciòn para crear al clasificador mediante el Kernel linear


In [38]:
def entrMod():
    
    ''' Se procede a entrenar el modelo y predecir la respuesta mediante las pruebas realizadas '''

clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

    
print(entrMod.__doc__)

 Se procede a entrenar el modelo y predecir la respuesta mediante las pruebas realizadas 
